use_frameworks!
platform :ios, '11.0'

# ignore all warnings from all dependencies
#inhibit_all_warnings!

target 'ExampleDoclineVideoSDK' do
  pod 'DoclineVideoSDK', '1.0.1'
end

target 'ExampleDoclineVideoSDKTests' do
  inherit! :search_paths
end


